[package]
name = "vimo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow="1.0"
clap = { version = "3.2.1", features = ["derive"] }
chrono = "0.4"
home="0.5"
dialoguer="0.10"
duct = "0.13.6"

